Repository MTES-MCT/qualicharge, pull requests merged in 2024-07, with the labels that each got.

#110 🔖(minor) bump release to 0.10.0
  src/api/CHANGELOG.md
  src/api/pyproject.toml
  src/api/qualicharge/__init__.py
Labels: release

#116 Add Data7-based opendata service
  Makefile
  bin/data7
  bin/pipenv
  docker-compose.yml
  env.d/opendata
  src/opendata/.secrets.yaml
  src/opendata/CHANGELOG.md
  src/opendata/Dockerfile
  src/opendata/Pipfile
  src/opendata/Pipfile.lock
  src/opendata/Procfile
  src/opendata/data7.yaml
  src/opendata/settings.yaml
Labels: feature

#123 ⬆️(opendata) upgrade data7 to 0.6.0
  env.d/opendata
  src/opendata/CHANGELOG.md
  src/opendata/Pipfile
  src/opendata/Pipfile.lock
  src/opendata/settings.yaml
Labels: improvement

#124 🩹(api) improve Swagger data examples
  src/api/CHANGELOG.md
  src/api/qualicharge/models/dynamic.py
  src/api/qualicharge/models/static.py
Labels: improvement

#131 🐛(api) fix not thread-safe database session singleton
  src/api/CHANGELOG.md
  src/api/qualicharge/db.py
Labels: bug, improvement, API

#126 🔨(notebook) add example notebook that interacts with the database
  .gitignore
  docker-compose.yml
  env.d/notebook
  src/notebook/Dockerfile
  src/notebook/example.md
Labels: feature

#134 🔨 (notebook) add example of Metabase API
  env.d/notebook
  src/notebook/example.md
Labels: documentation

#143 🐛(api) make the `PointDeCharge.id_pdc_itinerance` field unique
  src/api/CHANGELOG.md
  src/api/qualicharge/migrations/versions/d1e96368f232_id_pdc_itinerance_should_be_unique.py
  src/api/qualicharge/schemas/core.py
Labels: bug, critical, API
